### ISSUE TITLE
Add testimonials to the website

### ISSUE THREAD

**Issue by DonaldKLee** [youthelpingyouthbc/youthelpingyouthbc.github.io#15]
Take some YHY testimonials that we have, and add them to our website

**Comment by kellyhum** [comment]
Also fix testimonial container height, currently the text goes past the headshot.
![image](https://user-images.githubusercontent.com/75543429/183528702-73e2c755-9d70-46a7-b44e-7bd12d4838dd.png)

**Comment by kellyhum** [comment]
And change the intensity of the drop shadow, currently a bit too dark
![image](https://user-images.githubusercontent.com/75543429/183529901-a66eaa9b-32a6-4488-b285-40dc31fb31c8.png)
